//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySimpleWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Diagnostics;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class mydbEntities : DbContext
    {
        public mydbEntities(string connectionStr = "name=mydbEntities")
            : base(connectionStr)
        {

            //this.Database.Log = log => Trace.TraceInformation($"REAL-SQL : {log}");
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();

            //https://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }

        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MyUser> MyUsers { get; set; }
    }
}
